#!/bin/sh

if [ "$#" -gt 0 ] ; then
  git add "$@"
fi

set -e

last_author=`git log --format='%an' HEAD^!`

if [ "$last_author" != "Raphael Isemann" ] ; then
  echo "Last commit was not by me, but by $last_author"
  exit 1
fi

git commit --amend -C HEAD

