#!/usr/bin/python

import fileinput
import sys
import re
import subprocess

cmd = ""
for i in range(1, len(sys.argv)):
  cmd += '"' + sys.argv[i] + '" '

for line in sys.stdin:
  pass
  ret = 0
  try:
    subprocess.check_output(cmd + line, shell=True, stderr=subprocess.STDOUT)
  except subprocess.CalledProcessError as e:
    ret =   e.returncode
  if ret == 0:
    sys.stdout.write(line)
