#!/bin/bash
set -e

if [[ $# -eq 0 ]] ; then
    echo 'Need to supply review number: $0 DXXXXXX'
    exit 1
fi

llvm-svn-update

llvm-apply $1
llvm-merge $1
git show
read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

llvm-commit
