#!/bin/bash
set -e
function cleanup_git {
  git fetch --all
  git checkout -B master origin/master
  git reset --hard
  git clean -fdx
  git svn rebase -l
  git svn rebase
}

cd ~/llvm/trunk
cleanup_git
cd tools/clang
cleanup_git
cd ../lldb
cleanup_git
