#!/bin/bash
set -e
cd ~/llvm/trunk
git fetch && (cd tools/clang && git fetch) && (cd tools/lldb && git fetch)  # Get matching revisions of both trees.
git checkout master
git svn rebase -l
(cd tools/clang &&
   git checkout master &&
   git svn rebase -l)
(cd tools/lldb &&
   git checkout master &&
   git svn rebase -l)
