#!/bin/bash
set -e
function cleanup_git {
  git fetch --all
  git checkout master
  git checkout -B master origin/master
  git checkout master
  git reset --hard
  git reset --hard HEAD^
  git clean -fdx
  git svn fetch
  git svn rebase -l
  git svn rebase
}

cd ~/llvm/upstream
cleanup_git
cd tools/clang
cleanup_git
cd ../lldb
cleanup_git
