#!/usr/bin/python

import sys

for line in sys.stdin:
    header = line.strip()
    module_name = header.replace("/", "_")
    print("  module \"" + module_name + "\" { header \"" + header + "\" export * }")
