#!/usr/bin/env python

import sys

f = open(sys.argv[1], "r")
lines = f.readlines()
f.close()

f = open(sys.argv[1], "w")
for line in lines:
  if '"' + sys.argv[2] + '"' not in line:
    f.write(line)
f.close()
