#!/usr/bin/python

import os
import sys
import time

def check_pid(pid):
    """ Check For the existence of a unix pid. """
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    else:
        return True

while check_pid(int(sys.argv[1])):
  time.sleep(1)
