#!/usr/bin/python

import os
import sys

def check_pid(pid):        
    """ Check For the existence of a unix pid. """
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    else:
        return True

while True:
  if not check_pid(int(sys.argv[1])):
    break
